import type { StockPositionItem } from "@project/shared-types";

export const MOCK_STOCK_PORTFOLIO_DATA: StockPositionItem[] = [
  {
    name: "Broadcom",
    ticker: "AVGO",
    currentPrice: 1245.6,
    priceChange: 2.15,
    priceChangePercentage: 1,
    units: 2,
    positionPrincipal: 2300.0,
    positionValue: 2491.2,
  },
  {
    name: "JPMorgan Chase",
    ticker: "JPM",
    currentPrice: 172.45,
    priceChange: 0.85,
    priceChangePercentage: 1,
    units: 20,
    positionPrincipal: 3200.0,
    positionValue: 3449.0,
  },
  {
    name: "Eli Lilly",
    ticker: "LLY",
    currentPrice: 752.1,
    priceChange: 1.42,
    priceChangePercentage: 1,
    units: 4,
    positionPrincipal: 2800.0,
    positionValue: 3008.4,
  },
  {
    name: "PepsiCo",
    ticker: "PEP",
    currentPrice: 168.9,
    priceChange: -0.35,
    priceChangePercentage: 1,
    units: 15,
    positionPrincipal: 2600.0,
    positionValue: 2533.5,
  },
  {
    name: "Costco",
    ticker: "COST",
    currentPrice: 715.3,
    priceChange: 0.45,
    priceChangePercentage: 1,
    units: 6,
    positionPrincipal: 4000.0,
    positionValue: 4291.8,
  },
  {
    name: "Chevron",
    ticker: "CVX",
    currentPrice: 148.12,
    priceChange: -1.2,
    priceChangePercentage: 1,
    units: 25,
    positionPrincipal: 3800.0,
    positionValue: 3703.0,
  },
  {
    name: "Walt Disney",
    ticker: "DIS",
    currentPrice: 110.45,
    priceChange: 2.3,
    priceChangePercentage: 1,
    units: 30,
    positionPrincipal: 3000.0,
    positionValue: 3313.5,
  },
  {
    name: "Visa",
    ticker: "V",
    currentPrice: 278.5,
    priceChange: 0.15,
    priceChangePercentage: 1,
    units: 12,
    positionPrincipal: 3200.0,
    positionValue: 3342.0,
  },
];
